
var g;g||(g=typeof Module !== 'undefined' ? Module : {});g.bg||(g.bg=0);g.bg++;
g.ENVIRONMENT_IS_PTHREAD||function(a){function b(n,t,r,v){if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)require("fs").readFile(n,function(y,B){y?v(y):r(B.buffer)});else{var w=new XMLHttpRequest;w.open("GET",n,!0);w.responseType="arraybuffer";w.onprogress=function(y){var B=t;y.total&&(B=y.total);if(y.loaded){w.sf?g.Bf[n].loaded=y.loaded:(w.sf=!0,g.Bf||(g.Bf={}),g.Bf[n]={loaded:y.loaded,total:B});var E=B=y=0,R;for(R in g.Bf){var S=g.Bf[R];
y+=S.total;B+=S.loaded;E++}y=Math.ceil(y*g.bg/E);g.setStatus&&g.setStatus("Downloading data... ("+B+"/"+y+")")}else!g.Bf&&g.setStatus&&g.setStatus("Downloading data...")};w.onerror=function(){throw Error("NetworkError for: "+n);};w.onload=function(){if(200==w.status||304==w.status||206==w.status||0==w.status&&w.response)r(w.response);else throw Error(w.statusText+" : "+w.responseURL);};w.send(null)}}function c(n){console.error("package error:",n)}function d(){function n(w,y,B){this.start=w;this.end=
y;this.audio=B}function t(w){if(!w)throw"Loading data file failed."+Error().stack;if(!(w instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;w=new Uint8Array(w);n.prototype.Tg=w;w=a.files;for(var y=0;y<w.length;++y)n.prototype.sf[w[y].filename].onload();g.removeRunDependency("datafile_build/web/index.data")}g.FS_createPath("/","assets",!0,!0);g.FS_createPath("/assets","maps",!0,!0);g.FS_createPath("/assets","music",!0,!0);g.FS_createPath("/assets","textures",!0,!0);g.FS_createPath("/assets",
"sounds",!0,!0);n.prototype={sf:{},open:function(w,y){this.name=y;this.sf[y]=this;g.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.fg(this.Tg.subarray(this.start,this.end))},fg:function(w){g.FS_createDataFile(this.name,null,w,!0,!0,!0);g.removeRunDependency("fp "+this.name);this.sf[this.name]=null}};for(var r=a.files,v=0;v<r.length;++v)(new n(r[v].start,r[v].end,r[v].audio||0)).open("GET",r[v].filename);g.addRunDependency("datafile_build/web/index.data");g.xg||(g.xg={});
g.xg["build/web/index.data"]={hh:!1};m?(t(m),m=null):k=t}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,h("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));
var e=g.locateFile?g.locateFile("index.data",""):"index.data",f=a.remote_package_size,k=null,m=g.getPreloadedPackage?g.getPreloadedPackage(e,f):null;m||b(e,f,function(n){k?(k(n),k=null):m=n},c);g.calledRun?d():(g.preRun||(g.preRun=[]),g.preRun.push(d))}({files:[{filename:"/assets/icon.png",start:0,end:1272},{filename:"/assets/font.ttf",start:1272,end:27488},{filename:"/assets/atlas.dat",start:27488,end:29442},{filename:"/assets/atlas.png",start:29442,end:79783},{filename:"/assets/title.ttf",start:79783,
end:119691},{filename:"/assets/maps/pinacolada.ogg",start:119691,end:2054504,audio:1},{filename:"/assets/maps/peachBeach.ogg",start:2054504,end:4038439,audio:1},{filename:"/assets/maps/stoplight.ogg",start:4038439,end:6052081,audio:1},{filename:"/assets/maps/bright79.ogg",start:6052081,end:8391398,audio:1},{filename:"/assets/maps/forYou.ogg",start:8391398,end:11239951,audio:1},{filename:"/assets/music/intro.ogg",start:11239951,end:11295092,audio:1},{filename:"/assets/music/get.ogg",start:11295092,
end:11339935,audio:1},{filename:"/assets/music/reveal.ogg",start:11339935,end:11439476,audio:1},{filename:"/assets/music/view.ogg",start:11439476,end:11482561,audio:1},{filename:"/assets/textures/alpha-eye-right.png",start:11482561,end:11483104},{filename:"/assets/textures/compress",start:11483104,end:11483173},{filename:"/assets/textures/crawler.png",start:11483173,end:11546709},{filename:"/assets/textures/oxynoe.png",start:11546709,end:11646837},{filename:"/assets/textures/zenith-wowitos.png",start:11646837,
end:11677344},{filename:"/assets/textures/alpha.png",start:11677344,end:11770011},{filename:"/assets/textures/sei.png",start:11770011,end:11883582},{filename:"/assets/textures/mono-glow.png",start:11883582,end:11885293},{filename:"/assets/textures/quad-energy.png",start:11885293,end:11902643},{filename:"/assets/textures/nothing.png",start:11902643,end:11902711},{filename:"/assets/textures/alphapeek.png",start:11902711,end:11920796},{filename:"/assets/textures/sei-missiles.png",start:11920796,end:11936379},
{filename:"/assets/textures/quad-eyes.png",start:11936379,end:11937050},{filename:"/assets/textures/alpha-dizzy.png",start:11937050,end:11943537},{filename:"/assets/textures/oct.png",start:11943537,end:12167290},{filename:"/assets/textures/alpha-whites.png",start:12167290,end:12168861},{filename:"/assets/textures/boulder.png",start:12168861,end:12180572},{filename:"/assets/textures/zenith.png",start:12180572,end:12300620},{filename:"/assets/textures/mono.png",start:12300620,end:12352557},{filename:"/assets/textures/zenith-controller.png",
start:12352557,end:12366410},{filename:"/assets/textures/quad.png",start:12366410,end:12479594},{filename:"/assets/textures/oxynoe-flame.png",start:12479594,end:12482048},{filename:"/assets/textures/alpha-eye-left.png",start:12482048,end:12482599},{filename:"/assets/sounds/unpause.ogg",start:12482599,end:12492474,audio:1},{filename:"/assets/sounds/die.ogg",start:12492474,end:12516747,audio:1},{filename:"/assets/sounds/pat.ogg",start:12516747,end:12525090,audio:1},{filename:"/assets/sounds/win.ogg",
start:12525090,end:12574587,audio:1},{filename:"/assets/sounds/jump.ogg",start:12574587,end:12583596,audio:1},{filename:"/assets/sounds/back.ogg",start:12583596,end:12601683,audio:1},{filename:"/assets/sounds/select.ogg",start:12601683,end:12626337,audio:1},{filename:"/assets/sounds/wind3.ogg",start:12626337,end:12652029,audio:1},{filename:"/assets/sounds/vineboom.ogg",start:12652029,end:12680845,audio:1},{filename:"/assets/sounds/hit.ogg",start:12680845,end:12685901,audio:1},{filename:"/assets/sounds/pause.ogg",
start:12685901,end:12696719,audio:1}],remote_package_size:12696719,package_uuid:"80303800-7be1-4d54-bcf3-1f6198ce52a7"});var aa=Object.assign({},g),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="object"==typeof window,fa="function"==typeof importScripts,ha="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,ia="",ja,ka,la,fs,ma,na;
if(ha)ia=fa?require("path").dirname(ia)+"/":__dirname+"/",na=()=>{ma||(fs=require("fs"),ma=require("path"))},ja=function(a,b){na();a=ma.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")},la=a=>{a=ja(a,!0);a.buffer||(a=new Uint8Array(a));return a},ka=(a,b,c)=>{na();a=ma.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),ba=process.argv.slice(2),"undefined"!=typeof module&&(module.exports=g),process.on("uncaughtException",
function(a){if(!(a instanceof oa))throw a;}),process.on("unhandledRejection",function(a){throw a;}),da=(a,b)=>{if(noExitRuntime)throw process.exitCode=a,b;b instanceof oa||h("exiting due to exception: "+b);process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ea||fa)fa?ia=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ia=document.currentScript.src),ia=0!==ia.indexOf("blob:")?ia.substr(0,ia.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ja=a=>{var b=
new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},fa&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var l=g.print||console.log.bind(console),h=g.printErr||console.warn.bind(console);Object.assign(g,aa);aa=null;
g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);function pa(a){qa||(qa={});qa[a]||(qa[a]=1,h(a))}var qa,ra;g.wasmBinary&&(ra=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&p("no native wasm support detected");
function q(a,b,c="i8"){"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":u[a>>0]=b;break;case "i8":u[a>>0]=b;break;case "i16":sa[a>>1]=b;break;case "i32":x[a>>2]=b;break;case "i64":z=[b>>>0,(A=b,1<=+Math.abs(A)?0<A?(Math.min(+Math.floor(A/4294967296),4294967295)|0)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];x[a>>2]=z[0];x[a+4>>2]=z[1];break;case "float":C[a>>2]=b;break;case "double":ta[a>>3]=b;break;default:p("invalid type for setValue: "+c)}}
var ua,va=!1,wa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function xa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&wa)return wa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function D(a,b){return a?xa(F,a,b):""}
function ya(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var m=a.charCodeAt(++f);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function za(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Aa(a){var b=za(a)+1,c=Ca(b);c&&ya(a,u,c,b);return c}function Da(a){var b=za(a)+1,c=Ea(b);ya(a,u,c,b);return c}var Fa,u,F,sa,Ga,x,G,C,ta;
function Ha(){var a=ua.buffer;Fa=a;g.HEAP8=u=new Int8Array(a);g.HEAP16=sa=new Int16Array(a);g.HEAP32=x=new Int32Array(a);g.HEAPU8=F=new Uint8Array(a);g.HEAPU16=Ga=new Uint16Array(a);g.HEAPU32=G=new Uint32Array(a);g.HEAPF32=C=new Float32Array(a);g.HEAPF64=ta=new Float64Array(a)}var Ia,Ja=[],Ka=[],La=[],Ma=[];function Na(){var a=g.preRun.shift();Ja.unshift(a)}var Oa=0,Pa=null,Qa=null;function Ra(){Oa++;g.monitorRunDependencies&&g.monitorRunDependencies(Oa)}
function Sa(){Oa--;g.monitorRunDependencies&&g.monitorRunDependencies(Oa);if(0==Oa&&(null!==Pa&&(clearInterval(Pa),Pa=null),Qa)){var a=Qa;Qa=null;a()}}function p(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";h(a);va=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Ta(){return H.startsWith("data:application/octet-stream;base64,")}var H;H="index.wasm";if(!Ta()){var Ua=H;H=g.locateFile?g.locateFile(Ua,ia):ia+Ua}
function Va(){var a=H;try{if(a==H&&ra)return new Uint8Array(ra);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}catch(b){p(b)}}
function Wa(){if(!ra&&(ea||fa)){if("function"==typeof fetch&&!H.startsWith("file://"))return fetch(H,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+H+"'";return a.arrayBuffer()}).catch(function(){return Va()});if(ka)return new Promise(function(a,b){ka(H,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Va()})}
var A,z,Za={77320:function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1},77467:function(){return"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1},77701:function(a){"undefined"===typeof g.SDL2&&(g.SDL2={});var b=g.SDL2;a?b.capture={}:b.audio={};b.pf||("undefined"!==typeof AudioContext?b.pf=new AudioContext:"undefined"!==typeof webkitAudioContext&&
(b.pf=new webkitAudioContext),b.pf&&Xa(b.pf));return void 0===b.pf?-1:0},78194:function(){return g.SDL2.pf.sampleRate},78262:function(a,b,c,d){function e(){}function f(m){void 0!==k.capture.Ff&&(clearTimeout(k.capture.Ff),k.capture.Ff=void 0);k.capture.Qf=k.pf.createMediaStreamSource(m);k.capture.tf=k.pf.createScriptProcessor(b,a,1);k.capture.tf.onaudioprocess=function(n){void 0!==k&&void 0!==k.capture&&(n.outputBuffer.getChannelData(0).fill(0),k.capture.Yf=n.inputBuffer,Ya(c,[d]))};k.capture.Qf.connect(k.capture.tf);
k.capture.tf.connect(k.pf.destination);k.capture.stream=m}var k=g.SDL2;k.capture.Wf=k.pf.createBuffer(a,b,k.pf.sampleRate);k.capture.Wf.getChannelData(0).fill(0);k.capture.Ff=setTimeout(function(){k.capture.Yf=k.capture.Wf;Ya(c,[d])},b/k.pf.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},
79914:function(a,b,c,d){var e=g.SDL2;e.audio.tf=e.pf.createScriptProcessor(b,0,a);e.audio.tf.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.ng=f.outputBuffer,Ya(c,[d]))};e.audio.tf.connect(e.pf.destination)},80324:function(a,b){for(var c=g.SDL2,d=c.capture.Yf.numberOfChannels,e=0;e<d;++e){var f=c.capture.Yf.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var k=0;k<b;++k)q(a+
4*k,f[k],"float");else for(k=0;k<b;++k)q(a+4*(k*d+e),f[k],"float")}},80929:function(a,b){for(var c=g.SDL2,d=c.audio.ng.numberOfChannels,e=0;e<d;++e){var f=c.audio.ng.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var k=0;k<b;++k)f[k]=C[a+(k*d+e<<2)>>2]}},81409:function(a){var b=g.SDL2;if(a){void 0!==b.capture.Ff&&clearTimeout(b.capture.Ff);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();
for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==b.capture.tf&&(b.capture.tf.onaudioprocess=function(){},b.capture.tf.disconnect(),b.capture.tf=void 0);void 0!==b.capture.Qf&&(b.capture.Qf.disconnect(),b.capture.Qf=void 0);void 0!==b.capture.Wf&&(b.capture.Wf=void 0);b.capture=void 0}else void 0!=b.audio.tf&&(b.audio.tf.disconnect(),b.audio.tf=void 0),b.audio=void 0;void 0!==b.pf&&void 0===b.audio&&void 0===b.capture&&(b.pf.close(),b.pf=void 0)}};
function $a(a,b,c){a.addEventListener(b,c,{once:!0})}function Xa(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&$a(d,c,function(){"suspended"===a.state&&a.resume()})})})}function ab(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Ng;"number"==typeof c?void 0===b.Hf?I(c)():I(c)(b.Hf):c(void 0===b.Hf?null:b.Hf)}}}var bb=[];
function I(a){var b=bb[a];b||(a>=bb.length&&(bb.length=a+1),bb[a]=b=Ia.get(a));return b}function Ya(a,b){if("vi".includes("j")){var c=g.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}else I(a).apply(null,b)}function cb(a){a instanceof oa||"unwind"==a||da(1,a)}
var db=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},J=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=db(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},eb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},fb=a=>{if("/"===
a)return"/";a=J(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function gb(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ha)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){p("randomDevice")}}
function hb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=db(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}var ib=[];function jb(a,b){ib[a]={input:[],output:[],Df:b};kb(a,lb)}
var lb={open:function(a){var b=ib[a.node.rdev];if(!b)throw new K(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Df.flush(a.tty)},flush:function(a){a.tty.Df.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Df.qg)throw new K(60);for(var e=0,f=0;f<d;f++){try{var k=a.tty.Df.qg(a.tty)}catch(m){throw new K(29);}if(void 0===k&&0===e)throw new K(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Df.gg)throw new K(60);
try{for(var e=0;e<d;e++)a.tty.Df.gg(a.tty,b[c+e])}catch(f){throw new K(29);}d&&(a.node.timestamp=Date.now());return e}},nb={qg:function(a){if(!a.input.length){var b=null;if(ha){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=mb(b)}return a.input.shift()},gg:function(a,b){null===b||10===b?(l(xa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(l(xa(a.output,0)),a.output=[])}},ob={gg:function(a,b){null===b||10===b?(h(xa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(h(xa(a.output,0)),a.output=[])}},L={xf:null,yf:function(){return L.createNode(null,"/",16895,0)},createNode:function(a,
b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new K(63);L.xf||(L.xf={dir:{node:{wf:L.lf.wf,uf:L.lf.uf,lookup:L.lf.lookup,Rf:L.lf.Rf,rename:L.lf.rename,unlink:L.lf.unlink,rmdir:L.lf.rmdir,readdir:L.lf.readdir,symlink:L.lf.symlink},stream:{zf:L.mf.zf}},file:{node:{wf:L.lf.wf,uf:L.lf.uf},stream:{zf:L.mf.zf,read:L.mf.read,write:L.mf.write,jg:L.mf.jg,ug:L.mf.ug,Tf:L.mf.Tf}},link:{node:{wf:L.lf.wf,uf:L.lf.uf,readlink:L.lf.readlink},stream:{}},mg:{node:{wf:L.lf.wf,uf:L.lf.uf},stream:pb}});c=qb(a,b,
c,d);16384===(c.mode&61440)?(c.lf=L.xf.dir.node,c.mf=L.xf.dir.stream,c.kf={}):32768===(c.mode&61440)?(c.lf=L.xf.file.node,c.mf=L.xf.file.stream,c.nf=0,c.kf=null):40960===(c.mode&61440)?(c.lf=L.xf.link.node,c.mf=L.xf.link.stream):8192===(c.mode&61440)&&(c.lf=L.xf.mg.node,c.mf=L.xf.mg.stream);c.timestamp=Date.now();a&&(a.kf[b]=c,a.timestamp=c.timestamp);return c},jh:function(a){return a.kf?a.kf.subarray?a.kf.subarray(0,a.nf):new Uint8Array(a.kf):new Uint8Array(0)},og:function(a,b){var c=a.kf?a.kf.length:
0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.kf,a.kf=new Uint8Array(b),0<a.nf&&a.kf.set(c.subarray(0,a.nf),0))},Wg:function(a,b){if(a.nf!=b)if(0==b)a.kf=null,a.nf=0;else{var c=a.kf;a.kf=new Uint8Array(b);c&&a.kf.set(c.subarray(0,Math.min(b,a.nf)));a.nf=b}},lf:{wf:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.nf:40960===(a.mode&
61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Jg=4096;b.blocks=Math.ceil(b.size/b.Jg);return b},uf:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&L.Wg(a,b.size)},lookup:function(){throw rb[44];},Rf:function(a,b,c,d){return L.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=sb(b,c)}catch(f){}if(d)for(var e in d.kf)throw new K(55);
}delete a.parent.kf[a.name];a.parent.timestamp=Date.now();a.name=c;b.kf[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.kf[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=sb(a,b),d;for(d in c.kf)throw new K(55);delete a.kf[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.kf)a.kf.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=L.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new K(28);
return a.link}},mf:{read:function(a,b,c,d,e){var f=a.node.kf;if(e>=a.node.nf)return 0;a=Math.min(a.node.nf-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===u.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.kf||a.kf.subarray)){if(f)return a.kf=b.subarray(c,c+d),a.nf=d;if(0===a.nf&&0===e)return a.kf=b.slice(c,c+d),a.nf=d;if(e+d<=a.nf)return a.kf.set(b.subarray(c,c+d),e),d}L.og(a,e+
d);if(a.kf.subarray&&b.subarray)a.kf.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.kf[e+f]=b[c+f];a.nf=Math.max(a.nf,e+d);return d},zf:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.nf);if(0>b)throw new K(28);return b},jg:function(a,b,c){L.og(a.node,b+c);a.node.nf=Math.max(a.node.nf,b+c)},ug:function(a,b,c,d,e,f){if(0!==b)throw new K(28);if(32768!==(a.node.mode&61440))throw new K(43);a=a.node.kf;if(f&2||a.buffer!==Fa){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,
d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;c=65536*Math.ceil(c/65536);(f=tb(65536,c))?(F.fill(0,f,f+c),c=f):c=0;if(!c)throw new K(48);u.set(a,c)}else d=!1,c=a.byteOffset;return{rh:c,ah:d}},Tf:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new K(43);if(e&2)return 0;L.mf.write(a,b,0,d,c,!1);return 0}}};
function ub(a,b,c){var d="al "+a;ka(a,function(e){e||p('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Sa(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ra(d)}
var vb=null,wb={},xb=[],yb=1,zb=null,Ab=!0,K=null,rb={},Cb=(a,b={})=>{a=hb("/",a);if(!a)return{path:"",node:null};b=Object.assign({pg:!0,hg:0},b);if(8<b.hg)throw new K(32);a=db(a.split("/").filter(k=>!!k),!1);for(var c=vb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=sb(c,a[e]);d=J(d+"/"+a[e]);c.Ef&&(!f||f&&b.pg)&&(c=c.Ef.root);if(!f||b.Kf)for(f=0;40960===(c.mode&61440);)if(c=Bb(d),d=hb(eb(d),c),c=Cb(d,{hg:b.hg+1}).node,40<f++)throw new K(32);}return{path:d,node:c}},Db=a=>
{for(var b;;){if(a===a.parent)return a=a.yf.vg,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Eb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%zb.length},sb=(a,b)=>{var c;if(c=(c=Fb(a,"x"))?c:a.lf.lookup?0:2)throw new K(c,a);for(c=zb[Eb(a.id,b)];c;c=c.Cf){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.lf.lookup(a,b)},qb=(a,b,c,d)=>{a=new Gb(a,b,c,d);b=Eb(a.parent.id,a.name);a.Cf=zb[b];return zb[b]=a},Hb={r:0,"r+":2,w:577,
"w+":578,a:1089,"a+":1090},Ib=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},Fb=(a,b)=>{if(Ab)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Jb=(a,b)=>{try{return sb(a,b),20}catch(c){}return Fb(a,"wx")},Kb=(a=0)=>{for(;4096>=a;a++)if(!xb[a])return a;throw new K(33);},Mb=(a,b)=>{Lb||(Lb=function(){this.Vf={}},Lb.prototype={flags:{get:function(){return this.Vf.flags},set:function(c){this.Vf.flags=c}},
position:{get ih(){return this.Vf.position},set:function(c){this.Vf.position=c}}});a=Object.assign(new Lb,a);b=Kb(b);a.fd=b;return xb[b]=a},pb={open:a=>{a.mf=wb[a.node.rdev].mf;a.mf.open&&a.mf.open(a)},zf:()=>{throw new K(70);}},kb=(a,b)=>{wb[a]={mf:b}},Nb=(a,b)=>{var c="/"===b,d=!b;if(c&&vb)throw new K(10);if(!c&&!d){var e=Cb(b,{pg:!1});b=e.path;e=e.node;if(e.Ef)throw new K(10);if(16384!==(e.mode&61440))throw new K(54);}b={type:a,qh:{},vg:b,Ug:[]};a=a.yf(b);a.yf=b;b.root=a;c?vb=a:e&&(e.Ef=b,e.yf&&
e.yf.Ug.push(b))},Ob=(a,b,c)=>{var d=Cb(a,{parent:!0}).node;a=fb(a);if(!a||"."===a||".."===a)throw new K(28);var e=Jb(d,a);if(e)throw new K(e);if(!d.lf.Rf)throw new K(63);return d.lf.Rf(d,a,b,c)},Pb=(a,b)=>Ob(a,(void 0!==b?b:511)&1023|16384,0),Qb=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return Ob(a,b|8192,c)},Rb=(a,b)=>{if(!hb(a))throw new K(44);var c=Cb(b,{parent:!0}).node;if(!c)throw new K(44);b=fb(b);var d=Jb(c,b);if(d)throw new K(d);if(!c.lf.symlink)throw new K(63);c.lf.symlink(c,b,a)},Sb=
a=>{var b=Cb(a,{parent:!0}).node;if(!b)throw new K(44);var c=fb(a);a=sb(b,c);a:{try{var d=sb(b,c)}catch(f){d=f.qf;break a}var e=Fb(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new K(d);if(!b.lf.unlink)throw new K(63);if(a.Ef)throw new K(10);b.lf.unlink(b,c);b=Eb(a.parent.id,a.name);if(zb[b]===a)zb[b]=a.Cf;else for(b=zb[b];b;){if(b.Cf===a){b.Cf=a.Cf;break}b=b.Cf}},Bb=a=>{a=Cb(a).node;if(!a)throw new K(44);if(!a.lf.readlink)throw new K(28);return hb(Db(a.parent),a.lf.readlink(a))},Tb=(a,b)=>
{a=Cb(a,{Kf:!b}).node;if(!a)throw new K(44);if(!a.lf.wf)throw new K(63);return a.lf.wf(a)},Ub=a=>Tb(a,!0),Vb=(a,b)=>{a="string"==typeof a?Cb(a,{Kf:!0}).node:a;if(!a.lf.uf)throw new K(63);a.lf.uf(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},Xb=(a,b,c)=>{if(""===a)throw new K(44);if("string"==typeof b){var d=Hb[b];if("undefined"==typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=J(a);try{e=Cb(a,{Kf:!(b&
131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new K(20);}else e=Ob(a,c,0),d=!0;if(!e)throw new K(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new K(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==Ib(b)||b&512)?31:Fb(e,Ib(b)):44))throw new K(c);if(b&512){c=e;c="string"==typeof c?Cb(c,{Kf:!0}).node:c;if(!c.lf.uf)throw new K(63);if(16384===(c.mode&61440))throw new K(31);if(32768!==(c.mode&61440))throw new K(28);if(d=Fb(c,"w"))throw new K(d);
c.lf.uf(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Mb({node:e,path:Db(e),flags:b,seekable:!0,position:0,mf:e.mf,Yg:[],error:!1});e.mf.open&&e.mf.open(e);!g.logReadFiles||b&1||(Wb||(Wb={}),a in Wb||(Wb[a]=1));return e},Yb=a=>{if(null===a.fd)throw new K(8);a.dg&&(a.dg=null);try{a.mf.close&&a.mf.close(a)}catch(b){throw b;}finally{xb[a.fd]=null}a.fd=null},Zb=(a,b,c)=>{if(null===a.fd)throw new K(8);if(!a.seekable||!a.mf.zf)throw new K(70);if(0!=c&&1!=c&&2!=c)throw new K(28);a.position=a.mf.zf(a,b,c);
a.Yg=[]},$b=(a,b,c,d,e,f)=>{if(0>d||0>e)throw new K(28);if(null===a.fd)throw new K(8);if(0===(a.flags&2097155))throw new K(8);if(16384===(a.node.mode&61440))throw new K(31);if(!a.mf.write)throw new K(28);a.seekable&&a.flags&1024&&Zb(a,0,2);var k="undefined"!=typeof e;if(!k)e=a.position;else if(!a.seekable)throw new K(70);b=a.mf.write(a,b,c,d,e,f);k||(a.position+=b);return b},ac=()=>{K||(K=function(a,b){this.node=b;this.Xg=function(c){this.qf=c};this.Xg(a);this.message="FS error"},K.prototype=Error(),
K.prototype.constructor=K,[44].forEach(a=>{rb[a]=new K(a);rb[a].stack="<generic error, no stack>"}))},bc,cc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},dc=(a,b)=>{a="string"==typeof a?a:Db(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=J(a+"/"+c);try{Pb(d)}catch(e){}a=d}}return d},ec=(a,b,c,d)=>{a=J(("string"==typeof a?a:Db(a))+"/"+b);c=cc(c,d);return Ob(a,(void 0!==c?c:438)&4095|32768,0)},fc=(a,b,c,d,e,f)=>{var k=b;a&&(a="string"==typeof a?a:Db(a),k=b?J(a+"/"+b):a);a=
cc(d,e);k=Ob(k,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Vb(k,a|146);b=Xb(k,577);$b(b,c,0,c.length,0,f);Yb(b);Vb(k,a)}return k},gc=(a,b,c,d)=>{a=J(("string"==typeof a?a:Db(a))+"/"+b);b=cc(!!c,!!d);gc.sg||(gc.sg=64);var e=gc.sg++<<8|0;kb(e,{open:f=>{f.seekable=!1},close:()=>{d&&d.buffer&&d.buffer.length&&d(10)},read:(f,k,m,n)=>{for(var t=0,r=0;r<n;r++){try{var v=c()}catch(w){throw new K(29);}if(void 0===v&&0===
t)throw new K(6);if(null===v||void 0===v)break;t++;k[m+r]=v}t&&(f.node.timestamp=Date.now());return t},write:(f,k,m,n)=>{for(var t=0;t<n;t++)try{d(k[m+t])}catch(r){throw new K(29);}n&&(f.node.timestamp=Date.now());return t}});return Qb(a,b,e)},hc=a=>{if(!(a.Rg||a.Sg||a.link||a.kf)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");
if(ja)try{a.kf=mb(ja(a.url)),a.nf=a.kf.length}catch(b){throw new K(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}},ic=(a,b,c,d,e)=>{function f(){this.eg=!1;this.sf=[]}f.prototype.get=function(r){if(!(r>this.length-1||0>r)){var v=r%this.chunkSize;return this.rg(r/this.chunkSize|0)[v]}};f.prototype.fg=function(r){this.rg=r};f.prototype.kg=function(){var r=new XMLHttpRequest;r.open("HEAD",c,!1);r.send(null);if(!(200<=r.status&&300>r.status||304===r.status))throw Error("Couldn't load "+
c+". Status: "+r.status);var v=Number(r.getResponseHeader("Content-length")),w,y=(w=r.getResponseHeader("Accept-Ranges"))&&"bytes"===w;r=(w=r.getResponseHeader("Content-Encoding"))&&"gzip"===w;var B=1048576;y||(B=v);var E=this;E.fg(R=>{var S=R*B,Ba=(R+1)*B-1;Ba=Math.min(Ba,v-1);if("undefined"==typeof E.sf[R]){var qe=E.sf;if(S>Ba)throw Error("invalid range ("+S+", "+Ba+") or no bytes requested!");if(Ba>v-1)throw Error("only "+v+" bytes available! programmer error!");var O=new XMLHttpRequest;O.open("GET",
c,!1);v!==B&&O.setRequestHeader("Range","bytes="+S+"-"+Ba);O.responseType="arraybuffer";O.overrideMimeType&&O.overrideMimeType("text/plain; charset=x-user-defined");O.send(null);if(!(200<=O.status&&300>O.status||304===O.status))throw Error("Couldn't load "+c+". Status: "+O.status);S=void 0!==O.response?new Uint8Array(O.response||[]):mb(O.responseText||"");qe[R]=S}if("undefined"==typeof E.sf[R])throw Error("doXHR failed!");return E.sf[R]});if(r||!v)B=v=1,B=v=this.rg(0).length,l("LazyFiles on gzip forces download of the whole file when length is accessed");
this.Ig=v;this.Hg=B;this.eg=!0};if("undefined"!=typeof XMLHttpRequest){if(!fa)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new f;Object.defineProperties(k,{length:{get:function(){this.eg||this.kg();return this.Ig}},chunkSize:{get:function(){this.eg||this.kg();return this.Hg}}});var m=void 0}else m=c,k=void 0;var n=ec(a,b,d,e);k?n.kf=k:m&&(n.kf=null,n.url=m);Object.defineProperties(n,{nf:{get:function(){return this.kf.length}}});
var t={};Object.keys(n.mf).forEach(r=>{var v=n.mf[r];t[r]=function(){hc(n);return v.apply(null,arguments)}});t.read=(r,v,w,y,B)=>{hc(n);r=r.node.kf;if(B>=r.length)return 0;y=Math.min(r.length-B,y);if(r.slice)for(var E=0;E<y;E++)v[w+E]=r[B+E];else for(E=0;E<y;E++)v[w+E]=r.get(B+E);return y};n.mf=t;return n},kc=(a,b,c,d,e,f,k,m,n,t)=>{function r(y){function B(E){t&&t();m||fc(a,b,E,d,e,n);f&&f();Sa(w)}jc(y,v,B,()=>{k&&k();Sa(w)})||B(y)}var v=b?hb(J(a+"/"+b)):a,w="cp "+v;Ra(w);"string"==typeof c?ub(c,
y=>r(y),k):r(c)},M={},Lb,Wb;function lc(a,b,c){if("/"===b.charAt(0))return b;if(-100===a)a="/";else{a=xb[a];if(!a)throw new K(8);a=a.path}if(0==b.length){if(!c)throw new K(44);return a}return J(a+"/"+b)}
function mc(a,b,c){try{var d=a(b)}catch(e){if(e&&e.node&&J(b)!==J(Db(e.node)))return-54;throw e;}x[c>>2]=d.dev;x[c+4>>2]=0;x[c+8>>2]=d.ino;x[c+12>>2]=d.mode;x[c+16>>2]=d.nlink;x[c+20>>2]=d.uid;x[c+24>>2]=d.gid;x[c+28>>2]=d.rdev;x[c+32>>2]=0;z=[d.size>>>0,(A=d.size,1<=+Math.abs(A)?0<A?(Math.min(+Math.floor(A/4294967296),4294967295)|0)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];x[c+40>>2]=z[0];x[c+44>>2]=z[1];x[c+48>>2]=4096;x[c+52>>2]=d.blocks;x[c+56>>2]=d.atime.getTime()/1E3|0;x[c+60>>2]=
0;x[c+64>>2]=d.mtime.getTime()/1E3|0;x[c+68>>2]=0;x[c+72>>2]=d.ctime.getTime()/1E3|0;x[c+76>>2]=0;z=[d.ino>>>0,(A=d.ino,1<=+Math.abs(A)?0<A?(Math.min(+Math.floor(A/4294967296),4294967295)|0)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];x[c+80>>2]=z[0];x[c+84>>2]=z[1];return 0}var nc=void 0;function oc(){nc+=4;return x[nc-4>>2]}function pc(a){a=xb[a];if(!a)throw new K(8);return a}var qc=[],rc;rc=ha?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();
function sc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,k){b.drawElementsInstancedANGLE(c,d,e,f,k)})}
function tc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function uc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var vc=1,wc=[],N=[],xc=[],yc=[],zc=[],P=[],Ac=[],Bc=[],Q=[],Cc=[],Dc=[],Ec=[],Fc={},Gc={},Hc=4;function T(a){Ic||(Ic=a)}function Jc(a){for(var b=vc++,c=a.length;c<b;c++)a[c]=null;return b}function Kc(a,b){a.sf||(a.sf=a.getContext,a.getContext=function(d,e){e=a.sf(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.tg?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Lc(c,b):0}
function Lc(a,b){var c=Jc(Bc),d={kh:c,attributes:b,version:b.tg,Xf:a};a.canvas&&(a.canvas.$g=d);Bc[c]=d;("undefined"==typeof b.Mg||b.Mg)&&Mc(d);return c}
function Mc(a){a||(a=U);if(!a.Pg){a.Pg=!0;var b=a.Xf;sc(b);tc(b);uc(b);b.fh=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.lh=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.rf=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.rf)b.rf=b.getExtension("EXT_disjoint_timer_query");b.oh=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var Nc={},Ic,U,Oc=[];function Pc(a,b,c,d){for(var e=0;e<a;e++){var f=V[c](),k=f&&Jc(d);f?(f.name=k,d[k]=f):T(1282);x[b+4*e>>2]=k}}function Qc(a,b,c,d,e,f,k,m){b=N[b];if(a=V[a](b,c))d=m&&ya(a.name,F,m,d),e&&(x[e>>2]=d),f&&(x[f>>2]=a.size),k&&(x[k>>2]=a.type)}function Rc(a,b){G[a>>2]=b;G[a+4>>2]=(b-G[a>>2])/4294967296}
function Sc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&T(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=V.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>U.version){T(1282);return}d=2*(V.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>U.version){T(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=V.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":T(1280);return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:T(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:x[b+4*a>>2]=e[a];break;case 2:C[b+4*a>>2]=e[a];break;case 4:u[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){T(1280);
h("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:T(1280);h("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Rc(b,d);break;case 0:x[b>>2]=d;break;case 2:C[b>>2]=d;break;case 4:u[b>>0]=d?1:0}}else T(1281)}
function Tc(a,b,c,d){if(c){b=V.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:T(1280);return}else if(b instanceof WebGLBuffer)a=b.name|0;else{T(1280);return}break;default:T(1280);return}switch(d){case 1:Rc(c,a);break;case 0:x[c>>2]=a;break;case 2:C[c>>2]=a;break;case 4:u[c>>0]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else T(1281)}
function Uc(a){var b=za(a)+1,c=Ca(b);ya(a,F,c,b);return c}function Vc(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Wc(a){var b=a.Gf,c=a.Dg,d;if(!b)for(a.Gf=b={},a.Cg={},d=0;d<V.getProgramParameter(a,35718);++d){var e=V.getActiveUniform(a,d);var f=e.name;e=e.size;var k=Vc(f);k=0<k?f.slice(0,k):f;var m=a.ig;a.ig+=e;c[k]=[e,m];for(f=0;f<e;++f)b[m]=f,a.Cg[m++]=k}}
function W(a){var b=V.Lg;if(b){var c=b.Gf[a];"number"==typeof c&&(b.Gf[a]=c=V.getUniformLocation(b,b.Cg[a]+(0<c?"["+c+"]":"")));return c}T(1282)}function Xc(a,b,c,d){if(c)if(a=N[a],Wc(a),a=V.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:C[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:C[c+4*b>>2]=a[b]}else T(1281)}
function Yc(a,b,c,d){if(c)if(a=V.getVertexAttrib(a,b),34975==b)x[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:C[c>>2]=a;break;case 5:x[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:C[c+4*b>>2]=a[b];break;case 5:x[c+4*b>>2]=Math.fround(a[b])}else T(1281)}function Zc(a){a-=5120;return 0==a?u:1==a?F:2==a?sa:4==a?x:6==a?C:5==a||28922==a||28520==a||30779==a||30782==a?G:Ga}
function $c(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function ad(a,b,c,d,e){a=Zc(a);var f=$c(a),k=Hc;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<f)+k-1&-k)>>f)}var bd=[],cd=[];function dd(a){if(!va)try{a()}catch(b){cb(b)}}function ed(a){setTimeout(function(){dd(a)},1E4)}var fd=!1,gd=null,hd=0,jd=null,kd=0,ld=0,md=0,nd=0,od=[],pd={},qd,rd,sd,td=!1,ud=!1,vd=[];
function wd(){function a(){ud=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!xd){xd=!0;try{yd=!0}catch(c){yd=!1,l("warning: no blob constructor, cannot create blobs with mimetypes")}zd="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:yd?null:l("warning: no BlobBuilder");Ad="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;g.wg||"undefined"!=typeof Ad||(l("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.wg=!0);g.preloadPlugins.push({canHandle:function(c){return!g.wg&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var k=null;if(yd)try{k=new Blob([c],{type:Bd(d)}),k.size!==c.length&&(k=new Blob([(new Uint8Array(c)).buffer],{type:Bd(d)}))}catch(t){pa("Blob constructor present but fails: "+
t+"; falling back to blob builder")}k||(k=new zd,k.append((new Uint8Array(c)).buffer),k=k.getBlob());var m=Ad.createObjectURL(k),n=new Image;n.onload=()=>{n.complete||p("Image "+d+" could not be decoded");var t=document.createElement("canvas");t.width=n.width;t.height=n.height;t.getContext("2d").drawImage(n,0,0);Ad.revokeObjectURL(m);e&&e(c)};n.onerror=()=>{l("Image "+m+" could not be decoded");f&&f()};n.src=m}});g.preloadPlugins.push({canHandle:function(c){return!g.ph&&c.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(c,d,e,f){function k(){n||(n=!0,e&&e(c))}function m(){n||(n=!0,new Audio,f&&f())}var n=!1;if(yd){try{var t=new Blob([c],{type:Bd(d)})}catch(v){return m()}t=Ad.createObjectURL(t);var r=new Audio;r.addEventListener("canplaythrough",function(){k(r)},!1);r.onerror=function(){if(!n){l("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var v="",w=0,y=0,B=0;B<c.length;B++)for(w=w<<8|c[B],y+=8;6<=y;){var E=w>>y-6&63;y-=6;v+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[E]}2==
y?(v+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&3)<<4],v+="=="):4==y&&(v+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&15)<<2],v+="=");r.src="data:audio/x-"+d.substr(-3)+";base64,"+v;k(r)}};r.src=t;ed(function(){k(r)})}else return m()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",function(c){!ud&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function jc(a,b,c,d){wd();var e=!1;g.preloadPlugins.forEach(function(f){!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e}
function Cd(a,b,c,d){if(b&&g.Af&&a==g.canvas)return g.Af;var e;if(b){var f={antialias:!1,alpha:!1,tg:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var k in d)f[k]=d[k];if("undefined"!=typeof Nc&&(e=Kc(a,f)))var m=Bc[e].Xf}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof V||p("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.Af=m,b&&(U=Bc[e],g.Af=V=U&&U.Xf),g.sh=b,vd.forEach(function(n){n()}),wd());return m}
var Dd=!1,Ed=void 0,Fd=void 0;
function Gd(a,b){function c(){td=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Hd,Ed&&d.requestPointerLock(),td=!0,Fd?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=G[SDL.screen>>2]|8388608),Id(g.canvas),Jd()):Id(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Fd?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=G[SDL.screen>>2]&
-8388609),Id(g.canvas),Jd()):Id(d));if(g.onFullScreen)g.onFullScreen(td);if(g.onFullscreen)g.onFullscreen(td)}Ed=a;Fd=b;"undefined"==typeof Ed&&(Ed=!0);"undefined"==typeof Fd&&(Fd=!1);var d=g.canvas;Dd||(Dd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Hd(){if(!td)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Kd=0;function Ld(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Kd)Kd=b+1E3/60;else for(;b+2>=Kd;)Kd+=1E3/60;setTimeout(a,Math.max(Kd-b,0))}}
function Bd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Md=0,Nd=0,Od=0,Pd=0;
function Qd(a){if(ud)"mousemove"!=a.type&&"mozMovementX"in a?Od=Pd=0:(Od=a.movementX||a.mozMovementX||a.webkitMovementX||0,Pd=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Md=SDL.mh+Od,Nd=SDL.nh+Pd):(Md+=Od,Nd+=Pd);else{var b=g.canvas.getBoundingClientRect(),c=g.canvas.width,d=g.canvas.height,e="undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(f+b.top),e*=c/b.width,a*=d/b.height,Od=e-Md,Pd=a-Nd,Md=e,Nd=a)}}var Rd=[];function Jd(){var a=g.canvas;Rd.forEach(function(b){b(a.width,a.height)})}function Sd(a,b,c){Id(g.canvas,a,b);c||Jd()}
function Id(a,b,c){b&&c?(a.Zg=b,a.Og=c):(b=a.Zg,c=a.Og);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Fd?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var xd,yd,zd,Ad;
function Td(a,b){ld=a;md=b;if(jd)if(fd||(fd=!0),0==a)gd=function(){var d=Math.max(0,rd+b-rc())|0;setTimeout(sd,d)};else if(1==a)gd=function(){Ld(sd)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);fa?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}gd=function(){setImmediate(sd)}}}
function Ud(a,b,c,d,e){!jd||p("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");jd=a;kd=d;var f=hd;fd=!1;sd=function(){if(!va)if(0<od.length){var k=Date.now(),m=od.shift();m.Ng(m.Hf);if(qd){var n=qd,t=0==n%1?n-1:Math.floor(n);qd=m.eh?t:(8*n+(t+.5))/9}l('main loop blocker "'+m.name+'" took '+(Date.now()-k)+" ms");g.setStatus&&(k=g.statusMessage||"Please wait...",
m=qd,n=pd.gh,m?m<n?g.setStatus(k+" ("+(n-m)+"/"+n+")"):g.setStatus(k):g.setStatus(""));f<hd||setTimeout(sd,0)}else f<hd||(nd=nd+1|0,1==ld&&1<md&&0!=nd%md?gd():(0==ld&&(rd=rc()),va||g.preMainLoop&&!1===g.preMainLoop()||(dd(a),g.postMainLoop&&g.postMainLoop()),f<hd||("object"==typeof SDL&&SDL.audio&&SDL.audio.Vg&&SDL.audio.Vg(),gd())))};e||(b&&0<b?Td(0,1E3/b):Td(1,1),gd());if(c)throw"unwind";}var Vd={};
function Wd(){if(!Xd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Vd)void 0===Vd[b]?delete a[b]:a[b]=Vd[b];var c=[];for(b in a)c.push(b+"="+a[b]);Xd=c}return Xd}var Xd;
function Yd(a,b,c,d){this.id=a;this.y=this.x=0;this.cg=!1;this.Bg=this.Ag=0;this.width=b;this.height=c;this.zg=b;this.yg=c;this.title=d;this.attributes=Zd;this.buttons=0;this.keys=[];this.$f=[];this.lg=this.Mf=this.ag=this.Uf=this.If=this.Jf=this.Sf=this.Lf=this.Fg=this.Eg=this.Gg=this.title=null}function $d(a){return 0>=a||!X?null:X[a-1]}
var ae=null,Y=null,X=null,Zd=null,be={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function ce(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function de(){var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function ee(a){Y&&Y.lg&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||I(Y.lg)(Y.id,a))}function fe(a,b){if(Y){var c=ce(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.$f[a]=b;Y.Mf&&(d&&(b=2),I(Y.Mf)(Y.id,c,a,b,de()))}}}
function ge(){he()}function ie(){he()}function je(a){fe(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function ke(a){fe(a.keyCode,0)}function le(){if(Y)for(var a=0;a<Y.$f.length;++a)Y.$f[a]&&fe(a,0)}function me(a){Y&&(Qd(a),a.target==g.canvas&&Y.Jf&&I(Y.Jf)(Y.id,Md,Nd))}function ne(a){Y&&a.target==g.canvas&&Y.If&&I(Y.If)(Y.id,1)}function oe(a){Y&&a.target==g.canvas&&Y.If&&I(Y.If)(Y.id,0)}
function pe(a,b){if(Y&&(Qd(a),a.target==g.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Y.buttons&=~(1<<c);Y.Sf&&I(Y.Sf)(Y.id,c,b,de())}}function re(a){Y&&pe(a,1)}function se(a){Y&&pe(a,0)}
function te(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);if(Y&&Y.Uf&&a.target==g.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;I(Y.Uf)(Y.id,b,c);a.preventDefault()}}
function ue(){Y&&Y.Gg&&dd(function(){I(Y.Gg)(Y.id,Y.width,Y.height)})}function ve(){Y&&Y.Lf&&dd(function(){I(Y.Lf)(Y.id,Y.width,Y.height)})}var we={},xe=[],ye=null;
function he(){if(nd!==ye||!nd){xe=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:[];ye=nd;for(var a=0;a<xe.length;++a){var b=xe[a];if(b){we[a]||(l("glfw joystick connected:",a),we[a]={id:Aa(b.id),dh:b.buttons.length,bh:b.axes.length,buttons:Ca(b.buttons.length),axes:Ca(4*b.axes.length)});for(var c=we[a],d=0;d<b.buttons.length;++d)q(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)q(c.axes+4*d,b.axes[d],"float")}else we[a]&&(l("glfw joystick disconnected",
a),ze(we[a].id),ze(we[a].buttons),ze(we[a].axes),delete we[a])}}}
function Ae(a){function b(m){var n="/.glfw_dropped_files/"+m.name.replace(/\//g,"_"),t=new FileReader;t.onloadend=v=>{if(2!=t.readyState)++f,l("failed to read dropped file: "+m.name+": "+t.error);else{var w=new Uint8Array(v.target.result);v={};v.flags=v.flags||577;var y=Xb(n,v.flags,v.mode);if("string"==typeof w){var B=new Uint8Array(za(w)+1);w=ya(w,B,0,B.length);$b(y,B,0,w,void 0,v.Kg)}else if(ArrayBuffer.isView(w))$b(y,w,0,w.byteLength,void 0,v.Kg);else throw Error("Unsupported data type");Yb(y);
if(++f===e){I(Y.ag)(Y.id,e,c);for(v=0;v<d.length;++v)ze(d[v]);ze(c)}}};t.readAsArrayBuffer(m);var r=Aa(n);d.push(r);q(c+4*k,r,"i8*")}if(Y&&Y.ag&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Ca(4*a.dataTransfer.files.length),d=[],e=a.dataTransfer.files.length,f=0;dc("/",".glfw_dropped_files");for(var k=0;k<e;++k)b(a.dataTransfer.files[k]);return!1}}function Be(a){if(Y&&Y.ag)return a.preventDefault(),!1}
function Gb(a,b,c,d){a||(a=this);this.parent=a;this.yf=a.yf;this.Ef=null;this.id=yb++;this.name=b;this.mode=c;this.lf={};this.mf={};this.rdev=d}Object.defineProperties(Gb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Sg:{get:function(){return 16384===(this.mode&61440)}},Rg:{get:function(){return 8192===(this.mode&61440)}}});ac();
zb=Array(4096);Nb(L,"/");Pb("/tmp");Pb("/home");Pb("/home/web_user");(()=>{Pb("/dev");kb(259,{read:()=>0,write:(b,c,d,e)=>e});Qb("/dev/null",259);jb(1280,nb);jb(1536,ob);Qb("/dev/tty",1280);Qb("/dev/tty1",1536);var a=gb();gc("/dev","random",a);gc("/dev","urandom",a);Pb("/dev/shm");Pb("/dev/shm/tmp")})();
(()=>{Pb("/proc");var a=Pb("/proc/self");Pb("/proc/self/fd");Nb({yf:()=>{var b=qb(a,"fd",16895,73);b.lf={lookup:(c,d)=>{var e=xb[+d];if(!e)throw new K(8);c={parent:null,yf:{vg:"fake"},lf:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();g.FS_createPath=dc;g.FS_createDataFile=fc;g.FS_createPreloadedFile=kc;g.FS_unlink=Sb;g.FS_createLazyFile=ic;g.FS_createDevice=gc;for(var V,Z=0;32>Z;++Z)Oc.push(Array(Z));var Ce=new Float32Array(288);
for(Z=0;288>Z;++Z)bd[Z]=Ce.subarray(0,Z+1);var De=new Int32Array(288);for(Z=0;288>Z;++Z)cd[Z]=De.subarray(0,Z+1);g.requestFullscreen=function(a,b){Gd(a,b)};g.requestAnimationFrame=function(a){Ld(a)};g.setCanvasSize=function(a,b,c){Sd(a,b,c)};g.pauseMainLoop=function(){gd=null;hd++};g.resumeMainLoop=function(){hd++;var a=ld,b=md,c=jd;jd=null;Ud(c,0,!1,kd,!0);Td(a,b);gd()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};
g.createContext=function(a,b,c,d){return Cd(a,b,c,d)};function mb(a){var b=Array(za(a)+1);a=ya(a,b,0,b.length);b.length=a;return b}
var Ge={a:function(a,b,c,d){p("Assertion failed: "+D(a)+", at: "+[b?D(b):"unknown filename",c,d?D(d):"unknown function"])},Ha:function(a,b){I(a)(b)},f:function(a,b,c){nc=c;try{var d=pc(a);switch(b){case 0:var e=oc();return 0>e?-28:Mb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=oc(),d.flags|=e,0;case 5:return e=oc(),sa[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return x[Ee()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof M||!(f instanceof
K))throw f;return-f.qf}},Qa:function(a,b){try{var c=pc(a);return mc(Tb,c.path,b)}catch(d){if("undefined"==typeof M||!(d instanceof K))throw d;return-d.qf}},Ua:function(a,b,c){nc=c;try{var d=pc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=oc();return x[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=oc();if(!d.mf.Qg)throw new K(59);return d.mf.Qg(d,b,a);case 21523:return d.tty?
0:-59;case 21524:return d.tty?0:-59;default:p("bad ioctl syscall "+b)}}catch(f){if("undefined"==typeof M||!(f instanceof K))throw f;return-f.qf}},Na:function(a,b){try{return a=D(a),mc(Ub,a,b)}catch(c){if("undefined"==typeof M||!(c instanceof K))throw c;return-c.qf}},Ja:function(a,b,c){try{return b=D(b),b=lc(a,b),b=J(b),"/"===b[b.length-1]&&(b=b.substr(0,b.length-1)),Pb(b,c),0}catch(d){if("undefined"==typeof M||!(d instanceof K))throw d;return-d.qf}},Ma:function(a,b,c,d){try{b=D(b);var e=d&256;b=lc(a,
b,d&4096);return mc(e?Ub:Tb,b,c)}catch(f){if("undefined"==typeof M||!(f instanceof K))throw f;return-f.qf}},Va:function(a,b,c,d){nc=d;try{b=D(b);b=lc(a,b);var e=d?oc():0;return Xb(b,c,e).fd}catch(f){if("undefined"==typeof M||!(f instanceof K))throw f;return-f.qf}},Oa:function(a,b){try{return a=D(a),mc(Tb,a,b)}catch(c){if("undefined"==typeof M||!(c instanceof K))throw c;return-c.qf}},Ya:function(){return Date.now()},Wa:function(){return!0},Ia:function(a,b,c,d,e,f){try{var k=xb[e];if(k&&c&2){var m=
F.slice(a,a+b);k&&k.mf.Tf&&k.mf.Tf(k,m,f,b,d)}}catch(n){if("undefined"==typeof M||!(n instanceof K))throw n;return-n.qf}},j:function(){p("")},b:function(a,b,c){qc.length=0;var d;for(c>>=2;d=F[b++];)(d=105>d)&&c&1&&c++,qc.push(d?ta[c++>>1]:x[c]),++c;return Za[a].apply(null,qc)},g:rc,pa:function(a){V.activeTexture(a)},oa:function(a,b){V.attachShader(N[a],P[b])},Qc:function(a,b){V.beginQuery(a,Q[b])},Pa:function(a,b){V.rf.beginQueryEXT(a,Q[b])},vc:function(a){V.beginTransformFeedback(a)},na:function(a,
b,c){V.bindAttribLocation(N[a],b,D(c))},la:function(a,b){35051==a?V.Zf=b:35052==a&&(V.vf=b);V.bindBuffer(a,wc[b])},sc:function(a,b,c){V.bindBufferBase(a,b,wc[c])},tc:function(a,b,c,d,e){V.bindBufferRange(a,b,wc[c],d,e)},ka:function(a,b){V.bindFramebuffer(a,xc[b])},ja:function(a,b){V.bindRenderbuffer(a,yc[b])},wb:function(a,b){V.bindSampler(a,Cc[b])},ia:function(a,b){V.bindTexture(a,zc[b])},nb:function(a,b){V.bindTransformFeedback(a,Dc[b])},Ac:function(a){V.bindVertexArray(Ac[a])},ya:function(a){V.bindVertexArray(Ac[a])},
ha:function(a,b,c,d){V.blendColor(a,b,c,d)},ga:function(a){V.blendEquation(a)},fa:function(a,b){V.blendEquationSeparate(a,b)},ea:function(a,b){V.blendFunc(a,b)},da:function(a,b,c,d){V.blendFuncSeparate(a,b,c,d)},Ec:function(a,b,c,d,e,f,k,m,n,t){V.blitFramebuffer(a,b,c,d,e,f,k,m,n,t)},ca:function(a,b,c,d){2<=U.version?c?V.bufferData(a,F,d,c,b):V.bufferData(a,b,d):V.bufferData(a,c?F.subarray(c,c+b):b,d)},aa:function(a,b,c,d){2<=U.version?V.bufferSubData(a,b,F,d,c):V.bufferSubData(a,b,F.subarray(d,d+
c))},$:function(a){return V.checkFramebufferStatus(a)},_:function(a){V.clear(a)},Vb:function(a,b,c,d){V.clearBufferfi(a,b,c,d)},Wb:function(a,b,c){V.clearBufferfv(a,b,C,c>>2)},Yb:function(a,b,c){V.clearBufferiv(a,b,x,c>>2)},Xb:function(a,b,c){V.clearBufferuiv(a,b,G,c>>2)},Z:function(a,b,c,d){V.clearColor(a,b,c,d)},Y:function(a){V.clearDepth(a)},X:function(a){V.clearStencil(a)},Gb:function(a,b,c,d){return V.clientWaitSync(Ec[a],b,(c>>>0)+4294967296*d)},W:function(a,b,c,d){V.colorMask(!!a,!!b,!!c,!!d)},
V:function(a){V.compileShader(P[a])},U:function(a,b,c,d,e,f,k,m){2<=U.version?V.vf?V.compressedTexImage2D(a,b,c,d,e,f,k,m):V.compressedTexImage2D(a,b,c,d,e,f,F,m,k):V.compressedTexImage2D(a,b,c,d,e,f,m?F.subarray(m,m+k):null)},Vc:function(a,b,c,d,e,f,k,m,n){V.vf?V.compressedTexImage3D(a,b,c,d,e,f,k,m,n):V.compressedTexImage3D(a,b,c,d,e,f,k,F,n,m)},T:function(a,b,c,d,e,f,k,m,n){2<=U.version?V.vf?V.compressedTexSubImage2D(a,b,c,d,e,f,k,m,n):V.compressedTexSubImage2D(a,b,c,d,e,f,k,F,n,m):V.compressedTexSubImage2D(a,
b,c,d,e,f,k,n?F.subarray(n,n+m):null)},Uc:function(a,b,c,d,e,f,k,m,n,t,r){V.vf?V.compressedTexSubImage3D(a,b,c,d,e,f,k,m,n,t,r):V.compressedTexSubImage3D(a,b,c,d,e,f,k,m,n,F,r,t)},Tb:function(a,b,c,d,e){V.copyBufferSubData(a,b,c,d,e)},R:function(a,b,c,d,e,f,k,m){V.copyTexImage2D(a,b,c,d,e,f,k,m)},Q:function(a,b,c,d,e,f,k,m){V.copyTexSubImage2D(a,b,c,d,e,f,k,m)},Wc:function(a,b,c,d,e,f,k,m,n){V.copyTexSubImage3D(a,b,c,d,e,f,k,m,n)},P:function(){var a=Jc(N),b=V.createProgram();b.name=a;b.Pf=b.Nf=b.Of=
0;b.ig=1;N[a]=b;return a},O:function(a){var b=Jc(P);P[b]=V.createShader(a);return b},N:function(a){V.cullFace(a)},M:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=wc[d];e&&(V.deleteBuffer(e),e.name=0,wc[d]=null,d==V.Zf&&(V.Zf=0),d==V.vf&&(V.vf=0))}},L:function(a,b){for(var c=0;c<a;++c){var d=x[b+4*c>>2],e=xc[d];e&&(V.deleteFramebuffer(e),e.name=0,xc[d]=null)}},K:function(a){if(a){var b=N[a];b?(V.deleteProgram(b),b.name=0,N[a]=null):T(1281)}},Sc:function(a,b){for(var c=0;c<a;c++){var d=x[b+
4*c>>2],e=Q[d];e&&(V.deleteQuery(e),Q[d]=null)}},gb:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Q[d];e&&(V.rf.deleteQueryEXT(e),Q[d]=null)}},J:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=yc[d];e&&(V.deleteRenderbuffer(e),e.name=0,yc[d]=null)}},yb:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Cc[d];e&&(V.deleteSampler(e),e.name=0,Cc[d]=null)}},I:function(a){if(a){var b=P[a];b?(V.deleteShader(b),P[a]=null):T(1281)}},Hb:function(a){if(a){var b=Ec[a];b?(V.deleteSync(b),
b.name=0,Ec[a]=null):T(1281)}},G:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=zc[d];e&&(V.deleteTexture(e),e.name=0,zc[d]=null)}},mb:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Dc[d];e&&(V.deleteTransformFeedback(e),e.name=0,Dc[d]=null)}},zc:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2];V.deleteVertexArray(Ac[d]);Ac[d]=null}},wa:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2];V.deleteVertexArray(Ac[d]);Ac[d]=null}},F:function(a){V.depthFunc(a)},E:function(a){V.depthMask(!!a)},
D:function(a,b){V.depthRange(a,b)},C:function(a,b){V.detachShader(N[a],P[b])},B:function(a){V.disable(a)},A:function(a){V.disableVertexAttribArray(a)},z:function(a,b,c){V.drawArrays(a,b,c)},Lb:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},sa:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},ed:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},fd:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},Za:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},Lc:function(a,b){for(var c=Oc[a],d=0;d<a;d++)c[d]=
x[b+4*d>>2];V.drawBuffers(c)},ad:function(a,b){for(var c=Oc[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];V.drawBuffers(c)},ta:function(a,b){for(var c=Oc[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];V.drawBuffers(c)},y:function(a,b,c,d){V.drawElements(a,b,c,d)},Kb:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},ra:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},bd:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},cd:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},dd:function(a,b,c,d,e){V.drawElementsInstanced(a,
b,c,d,e)},_c:function(a,b,c,d,e,f){V.drawElements(a,d,e,f)},x:function(a){V.enable(a)},v:function(a){V.enableVertexAttribArray(a)},Pc:function(a){V.endQuery(a)},Ga:function(a){V.rf.endQueryEXT(a)},uc:function(){V.endTransformFeedback()},Jb:function(a,b){return(a=V.fenceSync(a,b))?(b=Jc(Ec),a.name=b,Ec[b]=a,b):0},u:function(){V.finish()},t:function(){V.flush()},s:function(a,b,c,d){V.framebufferRenderbuffer(a,b,c,yc[d])},r:function(a,b,c,d,e){V.framebufferTexture2D(a,b,c,zc[d],e)},Bc:function(a,b,c,
d,e){V.framebufferTextureLayer(a,b,zc[c],d,e)},q:function(a){V.frontFace(a)},p:function(a,b){Pc(a,b,"createBuffer",wc)},n:function(a,b){Pc(a,b,"createFramebuffer",xc)},Tc:function(a,b){Pc(a,b,"createQuery",Q)},rb:function(a,b){for(var c=0;c<a;c++){var d=V.rf.createQueryEXT();if(!d){for(T(1282);c<a;)x[b+4*c++>>2]=0;break}var e=Jc(Q);d.name=e;Q[e]=d;x[b+4*c>>2]=e}},m:function(a,b){Pc(a,b,"createRenderbuffer",yc)},zb:function(a,b){Pc(a,b,"createSampler",Cc)},Ze:function(a,b){Pc(a,b,"createTexture",zc)},
lb:function(a,b){Pc(a,b,"createTransformFeedback",Dc)},yc:function(a,b){Pc(a,b,"createVertexArray",Ac)},va:function(a,b){Pc(a,b,"createVertexArray",Ac)},o:function(a){V.generateMipmap(a)},Ye:function(a,b,c,d,e,f,k){Qc("getActiveAttrib",a,b,c,d,e,f,k)},Xe:function(a,b,c,d,e,f,k){Qc("getActiveUniform",a,b,c,d,e,f,k)},Ob:function(a,b,c,d,e){a=N[a];if(a=V.getActiveUniformBlockName(a,b))e&&0<c?(c=ya(a,F,e,c),d&&(x[d>>2]=c)):d&&(x[d>>2]=0)},Pb:function(a,b,c,d){if(d)if(a=N[a],35393==c)c=V.getActiveUniformBlockName(a,
b),x[d>>2]=c.length+1;else{if(a=V.getActiveUniformBlockParameter(a,b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)x[d+4*c>>2]=a[c];else x[d>>2]=a}else T(1281)},Rb:function(a,b,c,d,e){if(e)if(0<b&&0==c)T(1281);else{a=N[a];for(var f=[],k=0;k<b;k++)f.push(x[c+4*k>>2]);if(a=V.getActiveUniforms(a,f,d))for(b=a.length,k=0;k<b;k++)x[e+4*k>>2]=a[k]}else T(1281)},We:function(a,b,c,d){a=V.getAttachedShaders(N[a]);var e=a.length;e>b&&(e=b);x[c>>2]=e;for(b=0;b<e;++b)x[d+4*b>>2]=P.indexOf(a[b])},Ve:function(a,
b){return V.getAttribLocation(N[a],D(b))},Ue:function(a,b){Sc(a,b,4)},Ab:function(a,b,c){c?Rc(c,V.getBufferParameter(a,b)):T(1281)},Te:function(a,b,c){c?x[c>>2]=V.getBufferParameter(a,b):T(1281)},Se:function(){var a=V.getError()||Ic;Ic=0;return a},Re:function(a,b){Sc(a,b,2)},fc:function(a,b){return V.getFragDataLocation(N[a],D(b))},Qe:function(a,b,c,d){a=V.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;x[d>>2]=a},Bb:function(a,b,c){Tc(a,
b,c,1)},Eb:function(a,b){Sc(a,b,1)},wc:function(a,b,c){Tc(a,b,c,0)},Oe:function(a,b){Sc(a,b,0)},$a:function(a,b,c,d,e){if(0>d)T(1281);else if(e){if(a=V.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)x[e+4*b>>2]=a[b]}else T(1281)},hb:function(){T(1282)},Me:function(a,b,c,d){a=V.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?ya(a,F,d,b):0;c&&(x[c>>2]=b)},Ne:function(a,b,c){if(c)if(a>=vc)T(1281);else if(a=N[a],35716==b)a=V.getProgramInfoLog(a),null===a&&(a="(unknown error)"),
x[c>>2]=a.length+1;else if(35719==b){if(!a.Pf)for(b=0;b<V.getProgramParameter(a,35718);++b)a.Pf=Math.max(a.Pf,V.getActiveUniform(a,b).name.length+1);x[c>>2]=a.Pf}else if(35722==b){if(!a.Nf)for(b=0;b<V.getProgramParameter(a,35721);++b)a.Nf=Math.max(a.Nf,V.getActiveAttrib(a,b).name.length+1);x[c>>2]=a.Nf}else if(35381==b){if(!a.Of)for(b=0;b<V.getProgramParameter(a,35382);++b)a.Of=Math.max(a.Of,V.getActiveUniformBlockName(a,b).length+1);x[c>>2]=a.Of}else x[c>>2]=V.getProgramParameter(a,b);else T(1281)},
Aa:function(a,b,c){if(c){a=Q[a];b=2>U.version?V.rf.getQueryObjectEXT(a,b):V.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;Rc(c,d)}else T(1281)},Ca:function(a,b,c){if(c){a=V.rf.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else T(1281)},za:function(a,b,c){if(c){a=Q[a];b=2>U.version?V.rf.getQueryObjectEXT(a,b):V.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;Rc(c,d)}else T(1281)},Mc:function(a,b,c){if(c){a=V.getQueryParameter(Q[a],b);var d;"boolean"==
typeof a?d=a?1:0:d=a;x[c>>2]=d}else T(1281)},Ba:function(a,b,c){if(c){a=V.rf.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else T(1281)},Oc:function(a,b,c){c?x[c>>2]=V.getQuery(a,b):T(1281)},Da:function(a,b,c){c?x[c>>2]=V.rf.getQueryEXT(a,b):T(1281)},Le:function(a,b,c){c?x[c>>2]=V.getRenderbufferParameter(a,b):T(1281)},pb:function(a,b,c){c?C[c>>2]=V.getSamplerParameter(Cc[a],b):T(1281)},qb:function(a,b,c){c?x[c>>2]=V.getSamplerParameter(Cc[a],b):T(1281)},Je:function(a,
b,c,d){a=V.getShaderInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?ya(a,F,d,b):0;c&&(x[c>>2]=b)},Ie:function(a,b,c,d){a=V.getShaderPrecisionFormat(a,b);x[c>>2]=a.rangeMin;x[c+4>>2]=a.rangeMax;x[d>>2]=a.precision},He:function(a,b,c,d){if(a=V.getShaderSource(P[a]))b=0<b&&d?ya(a,F,d,b):0,c&&(x[c>>2]=b)},Ke:function(a,b,c){c?35716==b?(a=V.getShaderInfoLog(P[a]),null===a&&(a="(unknown error)"),x[c>>2]=a?a.length+1:0):35720==b?(a=V.getShaderSource(P[a]),x[c>>2]=a?a.length+1:0):x[c>>2]=V.getShaderParameter(P[a],
b):T(1281)},Ge:function(a){var b=Fc[a];if(!b){switch(a){case 7939:b=V.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Uc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=V.getParameter(a))||T(1280);b=b&&Uc(b);break;case 7938:b=V.getParameter(7938);b=2<=U.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Uc(b);break;case 35724:b=V.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),
b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Uc(b);break;default:T(1280)}Fc[a]=b}return b},Ub:function(a,b){if(2>U.version)return T(1282),0;var c=Gc[a];if(c)return 0>b||b>=c.length?(T(1281),0):c[b];switch(a){case 7939:return c=V.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return Uc(d)}),c=Gc[a]=c,0>b||b>=c.length?(T(1281),0):c[b];default:return T(1280),0}},Db:function(a,b,c,d,e){0>c?T(1281):e?(a=V.getSyncParameter(Ec[a],b),null!==a&&(x[e>>2]=a,d&&(x[d>>
2]=1))):T(1281)},Fe:function(a,b,c){c?C[c>>2]=V.getTexParameter(a,b):T(1281)},De:function(a,b,c){c?x[c>>2]=V.getTexParameter(a,b):T(1281)},pc:function(a,b,c,d,e,f,k){a=N[a];if(a=V.getTransformFeedbackVarying(a,b))k&&0<c?(c=ya(a.name,F,k,c),d&&(x[d>>2]=c)):d&&(x[d>>2]=0),e&&(x[e>>2]=a.size),f&&(x[f>>2]=a.type)},Qb:function(a,b){return V.getUniformBlockIndex(N[a],D(b))},Sb:function(a,b,c,d){if(d)if(0<b&&(0==c||0==d))T(1281);else{a=N[a];for(var e=[],f=0;f<b;f++)e.push(D(x[c+4*f>>2]));if(a=V.getUniformIndices(a,
e))for(b=a.length,f=0;f<b;f++)x[d+4*f>>2]=a[f]}else T(1281)},Ae:function(a,b){b=D(b);if(a=N[a]){Wc(a);var c=a.Gf,d=0,e=b,f=Vc(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Dg[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||V.getUniformLocation(a,b)))return d}else T(1281);return-1},Ce:function(a,b,c){Xc(a,b,c,2)},Be:function(a,b,c){Xc(a,b,c,0)},hc:function(a,b,c){Xc(a,b,c,0)},nc:function(a,b,c){Yc(a,b,c,0)},mc:function(a,b,c){Yc(a,b,c,0)},xe:function(a,b,c){c?x[c>>2]=V.getVertexAttribOffset(a,b):
T(1281)},ze:function(a,b,c){Yc(a,b,c,2)},ye:function(a,b,c){Yc(a,b,c,5)},we:function(a,b){V.hint(a,b)},db:function(a,b,c){for(var d=Oc[b],e=0;e<b;e++)d[e]=x[c+4*e>>2];V.invalidateFramebuffer(a,d)},cb:function(a,b,c,d,e,f,k){for(var m=Oc[b],n=0;n<b;n++)m[n]=x[c+4*n>>2];V.invalidateSubFramebuffer(a,m,d,e,f,k)},ve:function(a){return(a=wc[a])?V.isBuffer(a):0},ue:function(a){return V.isEnabled(a)},se:function(a){return(a=xc[a])?V.isFramebuffer(a):0},re:function(a){return(a=N[a])?V.isProgram(a):0},Rc:function(a){return(a=
Q[a])?V.isQuery(a):0},Xa:function(a){return(a=Q[a])?V.rf.isQueryEXT(a):0},qe:function(a){return(a=yc[a])?V.isRenderbuffer(a):0},xb:function(a){return(a=Cc[a])?V.isSampler(a):0},pe:function(a){return(a=P[a])?V.isShader(a):0},Ib:function(a){return V.isSync(Ec[a])},oe:function(a){return(a=zc[a])?V.isTexture(a):0},kb:function(a){return V.isTransformFeedback(Dc[a])},xc:function(a){return(a=Ac[a])?V.isVertexArray(a):0},ua:function(a){return(a=Ac[a])?V.isVertexArray(a):0},ne:function(a){V.lineWidth(a)},
me:function(a){a=N[a];V.linkProgram(a);a.Gf=0;a.Dg={}},jb:function(){V.pauseTransformFeedback()},le:function(a,b){3317==a&&(Hc=b);V.pixelStorei(a,b)},ke:function(a,b){V.polygonOffset(a,b)},fb:function(){T(1280)},eb:function(){T(1280)},Ea:function(a,b){V.rf.queryCounterEXT(Q[a],b)},$c:function(a){V.readBuffer(a)},je:function(a,b,c,d,e,f,k){if(2<=U.version)if(V.Zf)V.readPixels(a,b,c,d,e,f,k);else{var m=Zc(f);V.readPixels(a,b,c,d,e,f,m,k>>$c(m))}else(k=ad(f,e,c,d,k))?V.readPixels(a,b,c,d,e,f,k):T(1280)},
he:function(){},ge:function(a,b,c,d){V.renderbufferStorage(a,b,c,d)},Dc:function(a,b,c,d,e){V.renderbufferStorageMultisample(a,b,c,d,e)},ib:function(){V.resumeTransformFeedback()},fe:function(a,b){V.sampleCoverage(a,!!b)},tb:function(a,b,c){V.samplerParameterf(Cc[a],b,c)},sb:function(a,b,c){V.samplerParameterf(Cc[a],b,C[c>>2])},vb:function(a,b,c){V.samplerParameteri(Cc[a],b,c)},ub:function(a,b,c){V.samplerParameteri(Cc[a],b,x[c>>2])},ee:function(a,b,c,d){V.scissor(a,b,c,d)},de:function(){T(1280)},
ce:function(a,b,c,d){for(var e="",f=0;f<b;++f){var k=d?x[d+4*f>>2]:-1;e+=D(x[c+4*f>>2],0>k?void 0:k)}V.shaderSource(P[a],e)},be:function(a,b,c){V.stencilFunc(a,b,c)},ae:function(a,b,c,d){V.stencilFuncSeparate(a,b,c,d)},$d:function(a){V.stencilMask(a)},_d:function(a,b){V.stencilMaskSeparate(a,b)},Yd:function(a,b,c){V.stencilOp(a,b,c)},Xd:function(a,b,c,d){V.stencilOpSeparate(a,b,c,d)},Wd:function(a,b,c,d,e,f,k,m,n){if(2<=U.version)if(V.vf)V.texImage2D(a,b,c,d,e,f,k,m,n);else if(n){var t=Zc(m);V.texImage2D(a,
b,c,d,e,f,k,m,t,n>>$c(t))}else V.texImage2D(a,b,c,d,e,f,k,m,null);else V.texImage2D(a,b,c,d,e,f,k,m,n?ad(m,k,d,e,n):null)},Zc:function(a,b,c,d,e,f,k,m,n,t){if(V.vf)V.texImage3D(a,b,c,d,e,f,k,m,n,t);else if(t){var r=Zc(n);V.texImage3D(a,b,c,d,e,f,k,m,n,r,t>>$c(r))}else V.texImage3D(a,b,c,d,e,f,k,m,n,null)},Vd:function(a,b,c){V.texParameterf(a,b,c)},Ud:function(a,b,c){V.texParameterf(a,b,C[c>>2])},Td:function(a,b,c){V.texParameteri(a,b,c)},Sd:function(a,b,c){V.texParameteri(a,b,x[c>>2])},bb:function(a,
b,c,d,e){V.texStorage2D(a,b,c,d,e)},ab:function(a,b,c,d,e,f){V.texStorage3D(a,b,c,d,e,f)},Rd:function(a,b,c,d,e,f,k,m,n){if(2<=U.version)if(V.vf)V.texSubImage2D(a,b,c,d,e,f,k,m,n);else if(n){var t=Zc(m);V.texSubImage2D(a,b,c,d,e,f,k,m,t,n>>$c(t))}else V.texSubImage2D(a,b,c,d,e,f,k,m,null);else t=null,n&&(t=ad(m,k,e,f,n)),V.texSubImage2D(a,b,c,d,e,f,k,m,t)},Xc:function(a,b,c,d,e,f,k,m,n,t,r){if(V.vf)V.texSubImage3D(a,b,c,d,e,f,k,m,n,t,r);else if(r){var v=Zc(t);V.texSubImage3D(a,b,c,d,e,f,k,m,n,t,v,
r>>$c(v))}else V.texSubImage3D(a,b,c,d,e,f,k,m,n,t,null)},qc:function(a,b,c,d){a=N[a];for(var e=[],f=0;f<b;f++)e.push(D(x[c+4*f>>2]));V.transformFeedbackVaryings(a,e,d)},Qd:function(a,b){V.uniform1f(W(a),b)},Pd:function(a,b,c){if(2<=U.version)V.uniform1fv(W(a),C,c>>2,b);else{if(288>=b)for(var d=bd[b-1],e=0;e<b;++e)d[e]=C[c+4*e>>2];else d=C.subarray(c>>2,c+4*b>>2);V.uniform1fv(W(a),d)}},Nd:function(a,b){V.uniform1i(W(a),b)},Md:function(a,b,c){if(2<=U.version)V.uniform1iv(W(a),x,c>>2,b);else{if(288>=
b)for(var d=cd[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);V.uniform1iv(W(a),d)}},ec:function(a,b){V.uniform1ui(W(a),b)},ac:function(a,b,c){V.uniform1uiv(W(a),G,c>>2,b)},Ld:function(a,b,c){V.uniform2f(W(a),b,c)},Kd:function(a,b,c){if(2<=U.version)V.uniform2fv(W(a),C,c>>2,2*b);else{if(144>=b)for(var d=bd[2*b-1],e=0;e<2*b;e+=2)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2];else d=C.subarray(c>>2,c+8*b>>2);V.uniform2fv(W(a),d)}},Jd:function(a,b,c){V.uniform2i(W(a),b,c)},Id:function(a,
b,c){if(2<=U.version)V.uniform2iv(W(a),x,c>>2,2*b);else{if(144>=b)for(var d=cd[2*b-1],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);V.uniform2iv(W(a),d)}},dc:function(a,b,c){V.uniform2ui(W(a),b,c)},$b:function(a,b,c){V.uniform2uiv(W(a),G,c>>2,2*b)},Hd:function(a,b,c,d){V.uniform3f(W(a),b,c,d)},Gd:function(a,b,c){if(2<=U.version)V.uniform3fv(W(a),C,c>>2,3*b);else{if(96>=b)for(var d=bd[3*b-1],e=0;e<3*b;e+=3)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2],d[e+2]=C[c+
(4*e+8)>>2];else d=C.subarray(c>>2,c+12*b>>2);V.uniform3fv(W(a),d)}},Fd:function(a,b,c,d){V.uniform3i(W(a),b,c,d)},Ed:function(a,b,c){if(2<=U.version)V.uniform3iv(W(a),x,c>>2,3*b);else{if(96>=b)for(var d=cd[3*b-1],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);V.uniform3iv(W(a),d)}},cc:function(a,b,c,d){V.uniform3ui(W(a),b,c,d)},_b:function(a,b,c){V.uniform3uiv(W(a),G,c>>2,3*b)},Cd:function(a,b,c,d,e){V.uniform4f(W(a),b,c,d,e)},Bd:function(a,
b,c){if(2<=U.version)V.uniform4fv(W(a),C,c>>2,4*b);else{if(72>=b){var d=bd[4*b-1],e=C;c>>=2;for(var f=0;f<4*b;f+=4){var k=c+f;d[f]=e[k];d[f+1]=e[k+1];d[f+2]=e[k+2];d[f+3]=e[k+3]}}else d=C.subarray(c>>2,c+16*b>>2);V.uniform4fv(W(a),d)}},Ad:function(a,b,c,d,e){V.uniform4i(W(a),b,c,d,e)},zd:function(a,b,c){if(2<=U.version)V.uniform4iv(W(a),x,c>>2,4*b);else{if(72>=b)for(var d=cd[4*b-1],e=0;e<4*b;e+=4)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2],d[e+3]=x[c+(4*e+12)>>2];else d=x.subarray(c>>
2,c+16*b>>2);V.uniform4iv(W(a),d)}},bc:function(a,b,c,d,e){V.uniform4ui(W(a),b,c,d,e)},Zb:function(a,b,c){V.uniform4uiv(W(a),G,c>>2,4*b)},Mb:function(a,b,c){a=N[a];V.uniformBlockBinding(a,b,c)},yd:function(a,b,c,d){if(2<=U.version)V.uniformMatrix2fv(W(a),!!c,C,d>>2,4*b);else{if(72>=b)for(var e=bd[4*b-1],f=0;f<4*b;f+=4)e[f]=C[d+4*f>>2],e[f+1]=C[d+(4*f+4)>>2],e[f+2]=C[d+(4*f+8)>>2],e[f+3]=C[d+(4*f+12)>>2];else e=C.subarray(d>>2,d+16*b>>2);V.uniformMatrix2fv(W(a),!!c,e)}},Kc:function(a,b,c,d){V.uniformMatrix2x3fv(W(a),
!!c,C,d>>2,6*b)},Ic:function(a,b,c,d){V.uniformMatrix2x4fv(W(a),!!c,C,d>>2,8*b)},xd:function(a,b,c,d){if(2<=U.version)V.uniformMatrix3fv(W(a),!!c,C,d>>2,9*b);else{if(32>=b)for(var e=bd[9*b-1],f=0;f<9*b;f+=9)e[f]=C[d+4*f>>2],e[f+1]=C[d+(4*f+4)>>2],e[f+2]=C[d+(4*f+8)>>2],e[f+3]=C[d+(4*f+12)>>2],e[f+4]=C[d+(4*f+16)>>2],e[f+5]=C[d+(4*f+20)>>2],e[f+6]=C[d+(4*f+24)>>2],e[f+7]=C[d+(4*f+28)>>2],e[f+8]=C[d+(4*f+32)>>2];else e=C.subarray(d>>2,d+36*b>>2);V.uniformMatrix3fv(W(a),!!c,e)}},Jc:function(a,b,c,d){V.uniformMatrix3x2fv(W(a),
!!c,C,d>>2,6*b)},Gc:function(a,b,c,d){V.uniformMatrix3x4fv(W(a),!!c,C,d>>2,12*b)},wd:function(a,b,c,d){if(2<=U.version)V.uniformMatrix4fv(W(a),!!c,C,d>>2,16*b);else{if(18>=b){var e=bd[16*b-1],f=C;d>>=2;for(var k=0;k<16*b;k+=16){var m=d+k;e[k]=f[m];e[k+1]=f[m+1];e[k+2]=f[m+2];e[k+3]=f[m+3];e[k+4]=f[m+4];e[k+5]=f[m+5];e[k+6]=f[m+6];e[k+7]=f[m+7];e[k+8]=f[m+8];e[k+9]=f[m+9];e[k+10]=f[m+10];e[k+11]=f[m+11];e[k+12]=f[m+12];e[k+13]=f[m+13];e[k+14]=f[m+14];e[k+15]=f[m+15]}}else e=C.subarray(d>>2,d+64*b>>
2);V.uniformMatrix4fv(W(a),!!c,e)}},Hc:function(a,b,c,d){V.uniformMatrix4x2fv(W(a),!!c,C,d>>2,8*b)},Fc:function(a,b,c,d){V.uniformMatrix4x3fv(W(a),!!c,C,d>>2,12*b)},vd:function(a){a=N[a];V.useProgram(a);V.Lg=a},ud:function(a){V.validateProgram(N[a])},td:function(a,b){V.vertexAttrib1f(a,b)},rd:function(a,b){V.vertexAttrib1f(a,C[b>>2])},qd:function(a,b,c){V.vertexAttrib2f(a,b,c)},pd:function(a,b){V.vertexAttrib2f(a,C[b>>2],C[b+4>>2])},od:function(a,b,c,d){V.vertexAttrib3f(a,b,c,d)},nd:function(a,b){V.vertexAttrib3f(a,
C[b>>2],C[b+4>>2],C[b+8>>2])},md:function(a,b,c,d,e){V.vertexAttrib4f(a,b,c,d,e)},ld:function(a,b){V.vertexAttrib4f(a,C[b>>2],C[b+4>>2],C[b+8>>2],C[b+12>>2])},ob:function(a,b){V.vertexAttribDivisor(a,b)},qa:function(a,b){V.vertexAttribDivisor(a,b)},gd:function(a,b){V.vertexAttribDivisor(a,b)},id:function(a,b){V.vertexAttribDivisor(a,b)},_a:function(a,b){V.vertexAttribDivisor(a,b)},lc:function(a,b,c,d,e){V.vertexAttribI4i(a,b,c,d,e)},jc:function(a,b){V.vertexAttribI4i(a,x[b>>2],x[b+4>>2],x[b+8>>2],
x[b+12>>2])},kc:function(a,b,c,d,e){V.vertexAttribI4ui(a,b,c,d,e)},ic:function(a,b){V.vertexAttribI4ui(a,G[b>>2],G[b+4>>2],G[b+8>>2],G[b+12>>2])},oc:function(a,b,c,d,e){V.vertexAttribIPointer(a,b,c,d,e)},kd:function(a,b,c,d,e,f){V.vertexAttribPointer(a,b,c,!!d,e,f)},jd:function(a,b,c,d){V.viewport(a,b,c,d)},Fb:function(a,b,c,d){V.waitSync(Ec[a],b,(c>>>0)+4294967296*d)},Nb:function(){return!1},Ra:function(a,b,c){F.copyWithin(a,b,b+c)},e:function(a){var b=F.length;a>>>=0;if(2147483648<a)return!1;for(var c=
1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);e=e.min.call(e,2147483648,d+(65536-d%65536)%65536);a:{try{ua.grow(e-Fa.byteLength+65535>>>16);Ha();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},xa:function(a,b,c){a=I(a);Ud(a,b,c)},Cb:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Ka:function(a,b){var c=0;Wd().forEach(function(d,e){var f=b+c;e=x[a+4*e>>2]=f;for(f=0;f<d.length;++f)u[e++>>
0]=d.charCodeAt(f);u[e>>0]=0;c+=d.length+1});return 0},La:function(a,b){var c=Wd();x[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});x[b>>2]=d;return 0},h:function(a){Fe(a)},k:function(a){try{var b=pc(a);Yb(b);return 0}catch(c){if("undefined"==typeof M||!(c instanceof K))throw c;return c.qf}},Ta:function(a,b,c,d){try{a:{var e=pc(a);a=b;for(var f=b=0;f<c;f++){var k=x[a>>2],m=x[a+4>>2];a+=8;var n=e,t=k,r=m,v=void 0,w=u;if(0>r||0>v)throw new K(28);if(null===n.fd)throw new K(8);if(1===(n.flags&
2097155))throw new K(8);if(16384===(n.node.mode&61440))throw new K(31);if(!n.mf.read)throw new K(28);var y="undefined"!=typeof v;if(!y)v=n.position;else if(!n.seekable)throw new K(70);var B=n.mf.read(n,w,t,r,v);y||(n.position+=B);var E=B;if(0>E){var R=-1;break a}b+=E;if(E<m)break}R=b}x[d>>2]=R;return 0}catch(S){if("undefined"==typeof M||!(S instanceof K))throw S;return S.qf}},Fa:function(a,b,c,d,e){try{var f=pc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Zb(f,
a,d);z=[f.position>>>0,(A=f.position,1<=+Math.abs(A)?0<A?(Math.min(+Math.floor(A/4294967296),4294967295)|0)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];x[e>>2]=z[0];x[e+4>>2]=z[1];f.dg&&0===a&&0===d&&(f.dg=null);return 0}catch(k){if("undefined"==typeof M||!(k instanceof K))throw k;return k.qf}},Sa:function(a,b,c,d){try{a:{var e=pc(a);a=b;for(var f=b=0;f<c;f++){var k=x[a>>2],m=x[a+4>>2];a+=8;var n=$b(e,u,k,m);if(0>n){var t=-1;break a}b+=n}t=b}x[d>>2]=t;return 0}catch(r){if("undefined"==typeof M||
!(r instanceof K))throw r;return r.qf}},Pe:function(a,b,c,d){var e;for(e=0;e<X.length&&null!==X[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var f=e+1;if(0>=a||0>=b)f=0;else{d?Gd():Sd(a,b);for(e=0;e<X.length&&null==X[e];e++);d=0<Zd[139265];e==X.length&&(d?g.Af=Cd(g.canvas,!0,!0,{antialias:1<Zd[135181],depth:0<Zd[135173],stencil:0<Zd[135174],alpha:0<Zd[135172]}):wd());!g.Af&&d?f=0:(a=new Yd(f,a,b,c),f-1==X.length?X.push(a):X[f-1]=a,Y=a,f=a.id)}return f},w:function(){Zd=
be},rc:function(a){a:{if(a=$d(a)){a.Eg&&I(a.Eg)(a.id);X[a.id-1]=null;Y.id==a.id&&(Y=null);for(a=0;a<X.length;a++)if(null!==X[a]){a=void 0;break a}g.Af=void 0}a=void 0}return a},l:function(a,b,c){q(b,Md,"double");q(c,Nd,"double")},d:function(a,b,c){var d=0,e=0;if(a=$d(a))d=a.width,e=a.height;b&&q(b,d,"i32");c&&q(c,e,"i32")},Zd:function(a,b,c){q(b,0,"i32");q(c,0,"i32")},te:function(){return 1},ie:function(){return 0},H:function(){if(X)return 1;rc();Zd=be;X=[];Y=null;window.addEventListener("gamepadconnected",
ge,!0);window.addEventListener("gamepaddisconnected",ie,!0);window.addEventListener("keydown",je,!0);window.addEventListener("keypress",ee,!0);window.addEventListener("keyup",ke,!0);window.addEventListener("blur",le,!0);g.canvas.addEventListener("touchmove",me,!0);g.canvas.addEventListener("touchstart",re,!0);g.canvas.addEventListener("touchcancel",se,!0);g.canvas.addEventListener("touchend",se,!0);g.canvas.addEventListener("mousemove",me,!0);g.canvas.addEventListener("mousedown",re,!0);g.canvas.addEventListener("mouseup",
se,!0);g.canvas.addEventListener("wheel",te,!0);g.canvas.addEventListener("mousewheel",te,!0);g.canvas.addEventListener("mouseenter",ne,!0);g.canvas.addEventListener("mouseleave",oe,!0);g.canvas.addEventListener("drop",Ae,!0);g.canvas.addEventListener("dragover",Be,!0);Rd.push(function(a,b){if(Y){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Y.Ag=Y.x,Y.Bg=Y.y,Y.zg=Y.width,Y.yg=Y.height,Y.x=Y.y=0,Y.width=screen.width,Y.height=screen.height,
Y.cg=!0):1==Y.cg?(Y.x=Y.Ag,Y.y=Y.Bg,Y.width=Y.zg,Y.height=Y.yg,Y.cg=!1):Y.width!=a||Y.height!=b?(Y.width=a,Y.height=b):c=!1;c&&(Sd(Y.width,Y.height,!0),ue(),ve())}});return 1},Ee:function(){},ma:function(){},sd:function(a,b){if(a=$d(a)){var c=a.Jf;a.Jf=b;b=c}else b=null;return b},S:function(a){var b=ae;ae=a;return b},Dd:function(a,b){a=$d(a);if(!a)return null;var c=a.Lf;a.Lf=b;return c},hd:function(a,b){if(a=$d(a)){var c=a.Mf;a.Mf=b;b=c}else b=null;return b},Nc:function(a,b){if(a=$d(a)){var c=a.Sf;
a.Sf=b;b=c}else b=null;return b},Yc:function(a,b){if(a=$d(a)){var c=a.Uf;a.Uf=b;b=c}else b=null;return b},Cc:function(a,b){a=$d(a);if(!a)return null;var c=a.Fg;a.Fg=b;return c},Od:function(a,b,c){if(a=$d(a))a.x=b,a.y=c},ba:function(){},gc:function(){window.removeEventListener("gamepadconnected",ge,!0);window.removeEventListener("gamepaddisconnected",ie,!0);window.removeEventListener("keydown",je,!0);window.removeEventListener("keypress",ee,!0);window.removeEventListener("keyup",ke,!0);window.removeEventListener("blur",
le,!0);g.canvas.removeEventListener("touchmove",me,!0);g.canvas.removeEventListener("touchstart",re,!0);g.canvas.removeEventListener("touchcancel",se,!0);g.canvas.removeEventListener("touchend",se,!0);g.canvas.removeEventListener("mousemove",me,!0);g.canvas.removeEventListener("mousedown",re,!0);g.canvas.removeEventListener("mouseup",se,!0);g.canvas.removeEventListener("wheel",te,!0);g.canvas.removeEventListener("mousewheel",te,!0);g.canvas.removeEventListener("mouseenter",ne,!0);g.canvas.removeEventListener("mouseleave",
oe,!0);g.canvas.removeEventListener("drop",Ae,!0);g.canvas.removeEventListener("dragover",Be,!0);g.canvas.width=g.canvas.height=1;Y=X=null},c:function(a,b){Zd[a]=b},i:function(){}};
(function(){function a(e){g.asm=e.exports;ua=g.asm._e;Ha();Ia=g.asm.ef;Ka.unshift(g.asm.$e);Sa("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return Wa().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){h("failed to asynchronously prepare wasm: "+f);p(f)})}var d={a:Ge};Ra("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return h("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ra||
"function"!=typeof WebAssembly.instantiateStreaming||Ta()||H.startsWith("file://")||"function"!=typeof fetch?c(b):fetch(H,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){h("wasm streaming compile failed: "+f);h("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.$e).apply(null,arguments)};
var ze=g._free=function(){return(ze=g._free=g.asm.af).apply(null,arguments)},Ca=g._malloc=function(){return(Ca=g._malloc=g.asm.bf).apply(null,arguments)},Ee=g.___errno_location=function(){return(Ee=g.___errno_location=g.asm.cf).apply(null,arguments)};g._main=function(){return(g._main=g.asm.df).apply(null,arguments)};
var tb=g._emscripten_builtin_memalign=function(){return(tb=g._emscripten_builtin_memalign=g.asm.ff).apply(null,arguments)},Ea=g.stackAlloc=function(){return(Ea=g.stackAlloc=g.asm.gf).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.hf).apply(null,arguments)};g.dynCall_ji=function(){return(g.dynCall_ji=g.asm.jf).apply(null,arguments)};g.addRunDependency=Ra;g.removeRunDependency=Sa;g.FS_createPath=dc;g.FS_createDataFile=fc;g.FS_createPreloadedFile=kc;
g.FS_createLazyFile=ic;g.FS_createDevice=gc;g.FS_unlink=Sb;var He;function oa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Qa=function Ie(){He||Je();He||(Qa=Ie)};
function Je(a){function b(){if(!He&&(He=!0,g.calledRun=!0,!va)){g.noFSInit||bc||(bc=!0,ac(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?gc("/dev","stdin",g.stdin):Rb("/dev/tty","/dev/stdin"),g.stdout?gc("/dev","stdout",null,g.stdout):Rb("/dev/tty","/dev/stdout"),g.stderr?gc("/dev","stderr",null,g.stderr):Rb("/dev/tty1","/dev/stderr"),Xb("/dev/stdin",0),Xb("/dev/stdout",1),Xb("/dev/stderr",1));Ab=!1;ab(Ka);ab(La);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(Ke){var c=a,d=g._main;
c=c||[];var e=c.length+1,f=Ea(4*(e+1));x[f>>2]=Da(ca);for(var k=1;k<e;k++)x[(f>>2)+k]=Da(c[k-1]);x[(f>>2)+e]=0;try{var m=d(e,f);Fe(m)}catch(n){cb(n)}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=g.postRun.shift(),Ma.unshift(c);ab(Ma)}}a=a||ba;if(!(0<Oa)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Na();ab(Ja);0<Oa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},
1);b()},1)):b())}}g.run=Je;function Fe(a){if(!noExitRuntime){if(g.onExit)g.onExit(a);va=!0}da(a,new oa(a))}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Ke=!0;g.noInitialRun&&(Ke=!1);Je();
